routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});


Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

//check if the user is logged in
Route::group(['middleware' => ['auth']], function () {

    //put admin. in front of every admin route
    Route::prefix('admin')->name('admin.')->group(function () {

        //admin-only routes
        Route::group(['middleware' => ['is_admin']], function () {
            Route::resource('roles_update', 'SuperAdmin\AdminRoleController');
        });

        //admin/teacher-only routes
        Route::group(['middleware' => ['is_teacher']], function () {
            //course management routes
            Route::resource('courses', 'Admin\AdminCourseController');

            //assignment management routes
            Route::resource('courses.assignments', 'Admin\AdminAssignmentController');
            Route::resource('made_assignments', 'Admin\AdminMadeAssignmentsController');
            Route::get('/made_assignments/download/{path}/', 'Admin\AdminMadeAssignmentsController@downloadClientFile')->name('download-file');

            //notification management routes
            Route::resource('notifications', 'Admin\AdminNotificationController')->except('show');

            //forum management routes
            Route::resource('topics', 'Admin\AdminTopicController');
            Route::resource('topics.posts', 'Admin\AdminForumPostController')->except('index');
            Route::resource('topics.posts.replies', 'Admin\AdminReplyController')->except('index', 'show');
        });
    });

    //course routes
    Route::resource('courses', 'CourseController');
    Route::get('courses_status', 'CourseController@index')->name('courses');

    //assignment routes
    Route::resource('assignments', 'AssignmentController');
    Route::resource('download', 'AssignmentDownloadController');
    Route::get('/download/download/{path}/', 'AssignmentDownloadController@downloadClientFile')->name('download-assignment-file');

    //reviewed assignments
    Route::resource('reviewed_assignments', 'ReviewedAssignmentController');

    //profile page for user
    Route::resource('profile', 'ProfileController');

    //forum routes
    Route::prefix('forum')->group(function () {
        Route::get('/', 'TopicController@index')->name('forum');
        Route::get('/my-posts', 'ForumPostController@index')->name('my-posts');
        Route::resource('topics', 'TopicController');
        Route::resource('topics.posts', 'ForumPostController')->except('index');
        Route::resource('topics.posts.replies', 'ReplyController')->except('index', 'show');
    });
});

app/Models/Assignment.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Assignment extends Model
{
    // Each assignment belongs to one course
    public function course()
    {
        return $this->belongsTo(Course::class);
    }

    public function users()
    {
        //Automatically laravel looks for assignment_id, so we manually put it to the correct foreign_id from our table
        return $this->belongsToMany(User::class, 'user_has_assignments', 'assignments_id', 'assignments_id');
    }

    // Each assignment can have many users through user_has_assignments.
    public function user_has_assignment()
    {
        //Automatically laravel looks for assignment_id, so we manually put it to the correct foreign_id from our table
        return $this->hasOne(UserHasAssignment::class, 'assignments_id');
    }

}

app/Http/Controllers/AssignmentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Course;
use App\Models\UserHasAssignment;
use App\Models\UserHasCourses;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use App\Models\Assignment;
use Illuminate\Support\Facades\Response;

class AssignmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        // load all courses
        $courses = Course::all();
        // load all the assignments
        $assignments = Assignment::all();

        $user_assignments = UserHasAssignment::where('users_id', '=', Auth::id())->get();
        //return the assignment view
        return view('assignments/assignments_home', [
            'assignments' => $assignments,
            'courses' => $courses,
            'user_assignments' => $user_assignments,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        // Select all content from the selected assignment
        $assignment_contents = Assignment::find($id);
        $user_id = auth()->id();

        //select the user assignment
        $user_assignments = DB::table('user_has_assignments')
            ->where('assignments_id', '=', $assignment_contents->id)
            ->where('users_id', '=', $user_id)
            ->first();

        // Return the view where it is displayed with variable from the select query
        return view('assignments/assignment_content', compact('assignment_contents', 'user_assignments'));

    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $assignment_content)
    {
        //check if a file was uploaded and save is
        if ($request->file != Null) {
            $request->file->storeAs('files', $request->file->getClientOriginalName());
        }

        //check if a file was uploaded and save the location in user has assignments
        if ($request->file != Null){
            $user_id = auth()->id();

            $user_assignment = UserHasAssignment::where('assignments_id', '=', $assignment_content)
                ->where('users_id', '=', $user_id)
                ->first();

            //check if user_assignment is empty
            //if it is create a new user_has_assignment
            //if not update the assignment location
            if (!empty($user_assignment))
            {

                DB::table('user_has_assignments')
                    ->where('assignments_id', '=', $assignment_content)
                    ->where('users_id', '=', $user_id)
                    ->update(['assignment_location' => $request->file->getClientOriginalName()]);
                $succes = 'Het bestand is ingeleverd';
            }
            else
            {
               $user_assignment = new UserHasAssignment();
               $user_assignment->users_id = $user_id;
               $user_assignment->assignments_id = $assignment_content;
               $user_assignment->status_id = 1;
               $user_assignment->assignment_location = $request->file->getClientOriginalName();
               $user_assignment->save();
                $succes = 'Het bestand is ingeleverd';
            }
        }
        else {
            $succes = 'Er is een fout opgetreden, probeer het opnieuw';
        }


        //check if the user has this course
        $user_id = auth()->id();
        $course_id = Assignment::where('id', $assignment_content)->first('courses_id');
        $user_course = UserHasCourses::where('users_id', '=', $user_id)->where('courses_id', '=', $course_id->courses_id)->first();

        if (empty($user_course))
        {
            //if the user doesnt have this course insert course into db
            $user_has_course = new UserHasCourses();

            $user_has_course->users_id = $user_id;
            $user_has_course->courses_id = $course_id->courses_id;
            $user_has_course->status_id = 1;

            $user_has_course->save();
        }

        //get the assignment id and return the content view
        $assignment_contents = Assignment::find($assignment_content);

        return view('assignments/assignment_content', compact('assignment_contents', 'succes'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function download($id){
        // Load the required assignment data
        $assignment_contents = Assignment::find($id);
        // Search for the file that needs to be downloaded
        $file = public_path() . $assignment_contents->file_location;
        // Add needed headers
        $headers = array(
            'Content-Type: text/plain'
        );
        // Return with the file
        return Response::download($file, "Test_opdracht.txt", $headers);
    }
}

resources/views/assignments/assignment_content.blade.php
@extends('layouts.app')

@section('head')
    <link href="{{ asset('css/assignments.css') }}" rel="stylesheet">
@endsection

@section('content')
    <div class="container mt-2">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ $assignment_contents->name }}</div>
                    <div class="card-body">
                        <div class="card-title">
                            {{ $assignment_contents->description }}
                        </div>
                        <div class="card-body bg-light row">
                            <a href="{{route('download-assignment-file',  $assignment_contents->file_location)}}"

                               target="_blank">
                                <button class="btn"><i
                                        class="fa fa-download"></i> {!! $assignment_contents->file_location !!}
                                </button>
                            </a>
                        </div>
                        <div class="wrapper mt-2">
                            <video preload controls style="width:400px;"
                                   poster="/public/images/bootstrap_tutorial.png">
                                <source src="/videos/{{ $assignment_contents->video_location }}"
                                        type="video/mp4">
                                Je browser support geen mp4 videos, verander van browser!
                            </video>
                        </div>
                    </div>
                </div>

                <div class="card mt-2 mb-4">
                    <div class="card-header">Opdracht Inleveren</div>
                    <div class="card-body">
                        @if(isset($succes))
                            <div class="alert alert-success">{{ $succes }}</div>
                        @endif
                        @if(!empty($user_assignments->assignment_location))
                            <div class="alert alert-success">
                                Deze opdracht is ingeleverd op {{$user_assignments->updated_at}}
                            </div>
                        @endif
                        <form action="{{ route('assignments.update', [$assignment_contents]) }}" method="POST"
                              enctype="multipart/form-data">
                            @method('PATCH')
                            @csrf

                            <label for="name"></label>
                            <input class="form-control @error('file') is-invalid @enderror" type="file" name="file"
                                   id="file"
                                   value="{{ $assignment_contents->assignment_location }}"> <br>
                            <div class="mt-2">
                                <button type="submit" class="btn btn-primary">Opslaan</button>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/assignments/assignments_home.blade.php
@extends('layouts.app')

@section('head')
    <link href="{{ asset('css/assignments.css') }}" rel="stylesheet">
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div>
                <h2>Opdrachten van {{ $courses->name }} </h2><br>
            </div>
            <div class="container m-2">
                <div class="row">
                    <div class="col-md-2">
                        <form action="{{route('courses.show', $courses)}}" method="get">
                            {{--                    @method('PATCH')--}}
                            @csrf
                            <select class="form-control btn-secondary" id="filter" name="sort" onchange="this.form.submit()">
                                <option value="" hidden selected>Sorteer</option>
                                <option value="name_asc">Naam ↑</option>
                                <option value="name_desc">Naam ↓</option>
                                <option value="date_asc">Aangemaakt ↑</option>
                                <option value="date_desc">Aangemaakt ↓</option>
                            </select>
                        </form>
                    </div>
                </div>
            </div>
            <div class="container d-flex flex-wrap row justify-content-center">
                @foreach($assignments as $assignment)
                    <div class="col-lg-3 col-md-4 col-sm-12 mb-3 d-flex align-items-stretch">
                        <a href="{{route('assignments.show', $assignment)}}">
                            <div class="card rounded-0"
                                 style="border-color: #45B97C; border-width: 1px; padding-bottom: 50px;">
                                <div class="card-body">
                                    <h5 class="card-title">{{ $assignment->name }}</h5>

                                    @foreach($user_assignments as $user_assignment)
                                        @if($user_assignment->assignments_id == $assignment->id)
                                            @if($user_assignment->status_id == 2)
                                                <i class="fa fa-check align-self-end mr-3"  aria-hidden="true"></i>
                                            @endif
                                        @endif
                                    @endforeach
                                </div>
                            </div>
                        </a>
                    </div>
                @endforeach
            </div>
        </div>
@endsection

resources/views/assignments/reviewed_assignments_home.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-sm-11 dropdown mb-3 mt-3">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Filteren op:
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{{route('reviewed_assignments.index', ['course_name' => request('course_name'), 'course_name' => 'asc']) }}"> Cursus (A-Z)</a>
            <a class="dropdown-item" href="{{ route('reviewed_assignments.index', ['course_name' => request('course_name'), 'course_name' => 'desc']) }}">Cursus (Z-A)</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{route('reviewed_assignments.index', ['assignment_name' => request('assignment_name'), 'assignment_name' => 'asc']) }}">Opdracht (A-Z)</a>
            <a class="dropdown-item" href="{{route('reviewed_assignments.index', ['assignment_name' => request('assignment_name'), 'assignment_name' => 'desc']) }}">Opdracht (Z-A)</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{route('reviewed_assignments.index', ['rating' => request('rating'), 'rating' => 'asc']) }}">Cijfer (↓-↑)</a>
            <a class="dropdown-item" href="{{route('reviewed_assignments.index', ['rating' => request('rating'), 'rating' => 'desc']) }}">Cijfer (↑-↓)</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{route('reviewed_assignments.index', ['feedback' => request('feedback'), 'feedback' => 'asc']) }}">Feedback (A-Z)</a>
            <a class="dropdown-item" href="{{route('reviewed_assignments.index', ['feedback' => request('feedback'), 'feedback' => 'desc']) }}">Feedback (Z-A)</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{route('reviewed_assignments.index', ['updated_at' => request('updated_at'), 'updated_at' => 'asc']) }}">Datum (↓-↑)</a>
            <a class="dropdown-item" href="{{route('reviewed_assignments.index', ['updated_at' => request('updated_at'), 'updated_at' => 'desc']) }}">Datum (↑-↓)</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="/reviewed_assignments">Reset</a>
        </div>
    </div>

    <div class="container-fluid ml-4">
        <div class="row">
            <div class="d-sm-inline-flex mr-2" >
                <table id="dtHorizontalVerticalExample" class="table table-striped table-bordered table-sm "
                       cellspacing="0"
                       width="100%">
                    <thead>
                    <tr>
                        <th>Cursus</th>
                        <th>Opdracht</th>
                        <th>Cijfer</th>
                        <th>Feedback</th>
                        <th>Datum</th>
                    </tr>
                    </thead>
                    <tbody>

                    @if(!Empty($reviewed_assignments))

                            @foreach($reviewed_assignments as $reviewed_assignment)
                                @if(!empty($reviewed_assignment->rating))
                                <tr>
                                    <td>{{$reviewed_assignment->course_name}}</td>
                                    <td>{{$reviewed_assignment->assignment_name}}</td>
                                    <td>{{$reviewed_assignment->rating}}</td>
                                    <td>{{$reviewed_assignment->feedback}}</td>
                                    <td>{{$reviewed_assignment->updated_at}}</td>
                                </tr>
                                @endif
                            @endforeach
                    @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection