routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});


Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

//check if the user is logged in
Route::group(['middleware' => ['auth']], function () {

    //put admin. in front of every admin route
    Route::prefix('admin')->name('admin.')->group(function () {

        //admin-only routes
        Route::group(['middleware' => ['is_admin']], function () {
            Route::resource('roles_update', 'SuperAdmin\AdminRoleController');
        });

        //admin/teacher-only routes
        Route::group(['middleware' => ['is_teacher']], function () {
            //course management routes
            Route::resource('courses', 'Admin\AdminCourseController');

            //assignment management routes
            Route::resource('courses.assignments', 'Admin\AdminAssignmentController');
            Route::resource('made_assignments', 'Admin\AdminMadeAssignmentsController');
            Route::get('/made_assignments/download/{path}/', 'Admin\AdminMadeAssignmentsController@downloadClientFile')->name('download-file');

            //notification management routes
            Route::resource('notifications', 'Admin\AdminNotificationController')->except('show');

            //forum management routes
            Route::resource('topics', 'Admin\AdminTopicController');
            Route::resource('topics.posts', 'Admin\AdminForumPostController')->except('index');
            Route::resource('topics.posts.replies', 'Admin\AdminReplyController')->except('index', 'show');
        });
    });

    //course routes
    Route::resource('courses', 'CourseController');
    Route::get('courses_status', 'CourseController@index')->name('courses');

    //assignment routes
    Route::resource('assignments', 'AssignmentController');
    Route::resource('download', 'AssignmentDownloadController');
    Route::get('/download/download/{path}/', 'AssignmentDownloadController@downloadClientFile')->name('download-assignment-file');

    //reviewed assignments
    Route::resource('reviewed_assignments', 'ReviewedAssignmentController');

    //profile page for user
    Route::resource('profile', 'ProfileController');

    //forum routes
    Route::prefix('forum')->group(function () {
        Route::get('/', 'TopicController@index')->name('forum');
        Route::get('/my-posts', 'ForumPostController@index')->name('my-posts');
        Route::resource('topics', 'TopicController');
        Route::resource('topics.posts', 'ForumPostController')->except('index');
        Route::resource('topics.posts.replies', 'ReplyController')->except('index', 'show');
    });
});

resources/views/admin/assignment_create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Opdracht Aanmaken</div>
                    <div class="card-body">
                        <!-- Form for creating a assignment. You have to enter a name,
                             the course is already filled in and hidden -->
                        <form action="{{ route('admin.courses.assignments.store', $course) }}" method="POST" enctype="multipart/form-data">
                            @csrf

                            <label for="name">Naam:</label>
                            <input class="form-control @error('name') is-invalid @enderror" type="text" name="name"
                                   id="name" required><br>

                            <label for="description">Beschrijving:</label>
                            <textarea class="form-control" type="text" name="description" id="description"
                                      required></textarea> <br>

                            <label for="name">Upload bestand:</label>
                            <input class="form-control @error('file') is-invalid @enderror" type="file" name="file"
                                   id="file"> <br>

                            <label for="name">Upload video:</label>
                            <input class="form-control @error('video') is-invalid @enderror" type="file" name="video"
                                   id="video"> <br>

                            <div class="mt-2">
                                <div class="row">
                                    <div class="custom-control custom-checkbox col ml-3">
                                        <input type="hidden" name="end_assignment_check" value="0">

                                        <input type="checkbox"
                                               class="custom-control-input" id="defaultUnchecked1"
                                               name="end_assignment_check" value="1">

                                        <label class="custom-control-label" for="defaultUnchecked1">Eindopdracht</label>
                                    </div>
                                </div>

                                <div class="mt-2">
                                    <button type="submit" class="btn btn-primary">Opslaan</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/course_edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="d-flex justify-content-center"><h1>Admin cursus aanpassen</h1></div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Cursus aanpassen</div>

                    <div class="card-body">
                        <form action="{{ route('admin.courses.update', $course) }}" method="POST" enctype="multipart/form-data">
                            @method('PATCH')
                            @csrf

                            <label for="name">Naam:</label>
                            <input class="form-control" type="text" name="name" id="name"
                                   value="{{ $course->name }}" required> <br>

                            <label for="description">Beschrijving:</label>
                            <textarea class="form-control" name="description" id="description" rows="6"
                                      required>{{ $course->description }}</textarea> <br>

                            <label for="level">Niveau:</label>
                            <input class="form-control" type="number" name="level" id="level"
                                   value="{{ $course->level }}" required>

                            <div class="mt-2">
                                <button type="submit" class="btn btn-primary">Opslaan</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/courses.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-md-12">
                <h1>Cursus Beheer</h1>
                <form action="{{ route('admin.courses.create') }}" method="GET" class="float-right">
                    <button type="submit" class="float-right btn btn-primary ">Voeg een nieuwe cursus toe</button>
                </form>
            </div>
        </div>
        <div class="container m-2">
            <div class="row">
                <div class="col-md-2">
                    <form action="{{route('admin.courses.index')}}" method="get">
                        {{--                    @method('PATCH')--}}
                        @csrf
                        <select class="form-control form-control-sm" id="filter" name="sort"
                                onchange="this.form.submit()">
                            <option value="" disabled selected>Sorteer</option>
                            <option value="name_asc">Naam ↑</option>
                            <option value="name_desc">Naam ↓</option>
                            <option value="level_asc">Level ↑</option>
                            <option value="level_desc">Level ↓</option>
                            <option value="date_asc">Aangemaakt ↑</option>
                            <option value="date_desc">Aangemaakt ↓</option>
                        </select>
                    </form>
                </div>
            </div>
        </div>
        <div class="row">
            @foreach($courses as $course)
                <div class="col-xl-3 col-md-6 col-sm-11 d-flex mb-2">
                    <div class="card rounded-0"
                         style="border-color: #45B97C; border-width: 1px; width: 100%">
                        <div class="card-header bg-transparent">
                            <a href="{{route('admin.courses.assignments.index', $course)}}"
                               style="color: #FFC929; font-family: 'Segoe UI', serif; font-weight: bold; ">
                                {{$course->name}}
                            </a>
                            <div class="row-cols-md-4 row-cols-sm-12">
                                <form action="{{ route('admin.courses.edit', $course) }}" method="GET"
                                      class="float-xl-right float-xl-right float-md-left float-sm-left mr-2 ">
                                    <button type="submit" class="btn btn-primary"><i
                                            class="fas fa-edit"></i>
                                    </button>
                                </form>
                                <form action="{{ route('admin.courses.destroy', $course)}}" method="POST"
                                      class="float-xl-right float-xl-right mr-2 float-md-left float-sm-left">
                                    @method('delete')
                                    @csrf
                                    <button type="submit" name="id" value="Delete" class="btn btn-danger">
                                        <i class="fas fa-trash-alt"></i>
                                    </button>
                                </form>
                            </div>
                        </div>
                        <div class="card-body d-flex flex-column">
                            <p>{!! $course->description !!}</p>
                            <p class="mt-auto">Niveau: {!! $course->level !!}</p>
                        </div>
                    </div>
                </div>
            @endforeach

        </div>
@endsection

resources/views/admin/courses_create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Maak een nieuwe cursus aan </div>
                    <div class="card-body">

                        <form action="{{route('admin.courses.store')}}" method="POST">
                            @method('POST')
                            @csrf

                            <label for="name">Naam:</label>
                            <input class="form-control" type="text" name="name" id="name" required>

                            <label for="description">Beschrijving:</label>
                            <textarea class="form-control" type="text" name="description" id="description" required></textarea> <br>

                            <label for="level">Level:</label>
                            <input class="form-control" type="number" name="level" id="level" required>

                            <div class="mt-2">
                                <button type="submit" class="btn btn-primary">Maak cursus aan</button>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/forum_post_edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="mb-3">Bootcamp Forums</h1>

                <div class="card">
                    <div class="card-header h5">Post aanpassen</div>

                    <div class="card-body">
                        <form action="{{ route('admin.topics.posts.update', [$topic, $forum_post])}}" method="POST">
                            @method('PATCH')
                            @csrf

                            <label for="title">Naam van de post</label>
                            <input class="form-control" type="text" name="title" id="title"
                                   value="{{ $forum_post->title}}"> <br>

                            <label for="message">Berichttekst</label>
                            <textarea class="form-control" type="text" name="message"
                                      id="message" rows="4">{{ $forum_post->message}}</textarea> <br>

                            <div class="mt-2">
                                <button type="submit" class="btn btn-primary">Opslaan</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/forum_post_show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="h1 mb-3">Bootcamp Forums Beheer</div>

                <div class="h5 mt-2">
                    <a href="{{ route('admin.topics.index') }}">Forums</a>
                    @foreach($path as $link)
                        > <a href="{{ route('admin.topics.show', $link) }}">{{ $link->name }}</a>
                    @endforeach
                    > {{ $forum_post->title }}
                </div>

                <div class="card mb-3">
                    <div class="card-header border-bottom-0">
                        <div class="h4 mb-0">{{ $forum_post->title }}</div>
                    </div>

                    <div class="card-body border-top">
                        <div>{{ $forum_post->message }}</div> <br>

                        <div class="text-black-50">
                            Gepost door: {{ $forum_post->users->name }} <br>
                            Gepost op: {{ $forum_post->created_at }}

                            <div class="row mt-2">
                                <a href="{{ route('admin.topics.posts.edit', [$topic, $forum_post]) }}"
                                   class="btn btn-primary ml-3">Bewerk post</a>

                                <form action="{{ route('admin.topics.posts.destroy', [$topic, $forum_post])}}"
                                      method="POST">
                                    @method('delete')
                                    @csrf

                                    <button type="submit" class="btn btn-danger ml-2">
                                        Verwijder post
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>

                    <div class="card-body border-top bg-light">
                        <a href="{{ route('admin.topics.posts.replies.create', [$topic, $forum_post]) }}"
                           class="btn btn-primary mb-2">Reageer op dit bericht</a>

                        <div class="h5 mb-0">Reacties:</div>

                        <div class="mt-3">
                            <form action="{{route('admin.topics.posts.show', [$topic, $forum_post])}}" method="get">
                                <select id="filter" name="sort" onchange="this.form.submit()">
                                    <option value="" disabled selected>Sorteer</option>
                                    <option value="message_asc">Bericht ↑</option>
                                    <option value="message_desc">Bericht ↓</option>
                                    <option value="name_asc">Naam ↑</option>
                                    <option value="name_desc">Naam ↓</option>
                                    <option value="created_at_asc">Datum ↑</option>
                                    <option value="created_at_desc">Datum ↓</option>
                                </select>
                            </form>
                        </div>
                    </div>

                    @foreach($replies as $reply)
                        <div class="card-body border-top">
                            <div>{{ $reply->message }}</div>
                            <br>
                            <div class="text-black-50 mb-1">
                                Gepost door: {{ $reply->users->name }} <br>
                                Gepost op: {{ $reply->created_at }}
                            </div>

                            <div class="row mt-2">
                                <a href="{{ route('admin.topics.posts.replies.edit', [$topic, $forum_post, $reply]) }}"
                                   class="btn btn-primary ml-3">Bewerk reactie</a>

                                <form action="{{ route('admin.topics.posts.replies.destroy', [$topic, $forum_post, $reply])}}"
                                    method="POST">
                                    @method('delete')
                                    @csrf

                                    <button type="submit" class="btn btn-danger ml-2">
                                        Verwijder reactie
                                    </button>
                                </form>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/made_assignments.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-sm-11 dropdown mb-3 mt-3">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Filteren op:
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{{route('admin.made_assignments.index', ['name' => request('name'), 'name' => 'asc']) }}"> Naam (A-Z)</a>
            <a class="dropdown-item" href="{{ route('admin.made_assignments.index', ['name' => request('name'), 'name' => 'desc']) }}">Naam (Z-A)</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{route('admin.made_assignments.index', ['course_name' => request('course_name'), 'course_name' => 'asc']) }}">Cursus (A-Z)</a>
            <a class="dropdown-item" href="{{route('admin.made_assignments.index', ['course_name' => request('course_name'), 'course_name' => 'desc']) }}">Cursus (A-Z)</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{route('admin.made_assignments.index', ['assignment_name' => request('assignment_name'), 'assignment_name' => 'asc']) }}">Opdracht (A-Z)</a>
            <a class="dropdown-item" href="{{route('admin.made_assignments.index', ['assignment_name' => request('assignment_name'), 'assignment_name' => 'desc']) }}">Opdracht (Z-A)</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{route('admin.made_assignments.index', ['updated_at' => request('updated_at'), 'updated_at' => 'asc']) }}">Datum (↓-↑)</a>
            <a class="dropdown-item" href="{{route('admin.made_assignments.index', ['updated_at' => request('updated_at'), 'updated_at' => 'desc']) }}">Datum (↑-↓)</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{route('admin.made_assignments.index')}}">Reset</a>
        </div>
    </div>

    <div class="container-fluid ml-4">
        <div class="row ">
            <div class="d-sm-inline-flex mr-2" >
                <table id="dtHorizontalVerticalExample" class="table table-striped table-bordered table-sm "
                       cellspacing="0"
                       width="100%">
                    <thead>
                    <tr>
                        <th>Naam student</th>
                        <th>Cursus</th>
                        <th>Opdracht</th>
                        <th>Datum</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if(!Empty($made_assignments))
                        @foreach($made_assignments as $made_assignment)
                            <tr>
                                <td>{{$made_assignment->name}}</td>
                                <td>{{$made_assignment->course_name}}</td>
                                <td>{{$made_assignment->assignment_name}}</td>
                                <td>{{$made_assignment->updated_at}}</td>
                                <td><a href="{{route('admin.made_assignments.show',  $made_assignment->assignment_id)}}" class="btn btn-info"><i class="far fa-eye"></i><i class="fas fa-pen"></i></a></td>
                            </tr>
                        @endforeach
                    @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/notification_create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header h5">Nieuwe melding aanmaken</div>

                    <div class="card-body">
                        <form action="{{ route('admin.notifications.store') }}" method="POST">
                            @csrf

                            <label for="title">Titel van de melding (maak deze niet te lang)</label>
                            <input class="form-control" type="text" name="title" id="title"> <br>

                            <label for="message">Meldingstekst</label>
                            <textarea class="form-control" type="text" name="message"
                                      id="message" rows="4"></textarea> <br>

                            <div class="mt-2">
                                <button type="submit" class="btn btn-primary">Opslaan</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/notification_edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header h5">Melding aanpassen</div>

                    <div class="card-body">
                        <form action="{{ route('admin.notifications.update', $notification) }}" method="POST">
                            @csrf
                            @method('PATCH')

                            <label for="title">Titel van de melding (maak deze niet te lang)</label>
                            <input class="form-control" type="text" name="title" id="title"
                                   value="{{ $notification->title }}"> <br>

                            <label for="message">Meldingstekst</label>
                            <textarea class="form-control" type="text" name="message"
                                      id="message" rows="4">{{ $notification->message }}</textarea> <br>

                            <div class="mt-2">
                                <button type="submit" class="btn btn-primary">Opslaan</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/reply_create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="mb-3">Bootcamp Forums</h1>

                <div class="card">
                    <div class="card-header">
                        <h4 class="mt-1">Reageer op {{ $forum_post->title }}</h4>
                    </div>

                    <div class="card-body">
                        <form action="{{ route('admin.topics.posts.replies.store', [$topic, $forum_post]) }}" method="POST">
                            @method('POST')
                            @csrf

                            <textarea class="form-control" type="text" name="message"
                                      id="message" required></textarea> <br>

                            <button type="submit" class="btn btn-primary">Plaats reactie</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/role_edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="ml-4">
            <div class="row">
                <div class="col-12">
                    <!-- show al the user data as it is now -->
                    <div class="card-body">
                        Naam: {!! $user->name !!}<br>
                        Email: {!! $user->email !!}<br>
                        Student nummer: {!! $user->student_number !!}<br>
                        Rol: {!! $role->role !!}
                    </div>
                </div>
            </div>
            <div class="row ">
                <!-- form to change the role of the user -->
                <form action="{{ route('admin.roles_update.update', $user) }}" method="POST">
                    @method('PATCH')
                    @csrf
                    <label>
                        <select class="mr-4 form-control" name="role" id="role">
                            @foreach($roles as $role)
                                <option value="{{$role->id}}">{!! $role->role !!}</option>
                            @endforeach
                        </select>
                    </label>
                    <button type="submit" class="form-control">Wijzig</button>
                </form>
                <!-- form -->
            </div>
        </div>
    </div>
@endsection

resources/views/admin/role_update.blade.php
@extends('layouts.app')

@section('content')
    <div class="container m-2">
        <form action="{{route('admin.roles_update.index')}}" method="get">
            @csrf
            <select id="filter" name="sort" onchange="this.form.submit()">
                <option value="" disabled selected>Sorteer</option>
                <option value="name_asc">Naam ↑</option>
                <option value="name_desc">Naam ↓</option>
                <option value="email_asc">Email ↑</option>
                <option value="email_desc">Email ↓</option>
                <option value="student_number_asc">Student nummer ↑</option>
                <option value="student_number_desc">Student nummer ↓</option>
            </select>
        </form>
    </div>

    <div class="container-fluid">
        <div class="row ">
            <div class="d-sm-inline-flex mr-2 ml-4" style="overflow-x: auto">
                <!-- show the data of all the user in table -->
                <table id="dtHorizontalVerticalExample" class="table table-striped table-bordered table-sm "
                       cellspacing="0"
                       width="100%">
                    <thead>
                    <tr>
                        <th>Naam student</th>
                        <th>Email</th>
                        <th>Student nummer</th>
                        <th>Rol</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if(!Empty($users_role))
                        @foreach($users_role as $user_role)
                            <tr>
                                <td>{{$user_role['name']}}</td>
                                <td>{{$user_role['email']}}</td>
                                <td>{{$user_role['student_number']}}</td>
                                <td>{{$user_role['roles']['role']}}</td>
                                <td><a href="{{route('admin.roles_update.edit', $user_role['id'])}}" ><i class="fas fa-pen"></i></a></td>

                            </tr>
                        @endforeach
                    @endif

                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/topics.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="h1 mb-3">Bootcamp Forums Beheer</div>

                <div class="h5 mt-2">
                    Forums
                </div>

                <div class="card mb-3">
                    <div class="card-header border-bottom-0">
                        <div class="h4 mb-0">Onderwerpen</div>

                        <div class="mt-3">
                            <form action="{{route('admin.topics.index')}}" method="get">
                                <select id="filter" name="sort_topics" onchange="this.form.submit()">
                                    <option value="" disabled selected>Sorteer</option>
                                    <option value="name_asc">Naam ↑</option>
                                    <option value="name_desc">Naam ↓</option>
                                    <option value="created_at_asc">Datum ↑</option>
                                    <option value="created_at_desc">Datum ↓</option>
                                </select>
                            </form>
                        </div>
                    </div>

                    @foreach($topics as $topic)
                        <a class="h6 mb-0" href="{{ route('admin.topics.show', $topic) }}">
                            <div class="card-body border-top">
                                {{ $topic->name }}
                            </div>
                        </a>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endsection