routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});


Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

//check if the user is logged in
Route::group(['middleware' => ['auth']], function () {

    //put admin. in front of every admin route
    Route::prefix('admin')->name('admin.')->group(function () {

        //admin-only routes
        Route::group(['middleware' => ['is_admin']], function () {
            Route::resource('roles_update', 'SuperAdmin\AdminRoleController');
        });

        //admin/teacher-only routes
        Route::group(['middleware' => ['is_teacher']], function () {
            //course management routes
            Route::resource('courses', 'Admin\AdminCourseController');

            //assignment management routes
            Route::resource('courses.assignments', 'Admin\AdminAssignmentController');
            Route::resource('made_assignments', 'Admin\AdminMadeAssignmentsController');
            Route::get('/made_assignments/download/{path}/', 'Admin\AdminMadeAssignmentsController@downloadClientFile')->name('download-file');

            //notification management routes
            Route::resource('notifications', 'Admin\AdminNotificationController')->except('show');

            //forum management routes
            Route::resource('topics', 'Admin\AdminTopicController');
            Route::resource('topics.posts', 'Admin\AdminForumPostController')->except('index');
            Route::resource('topics.posts.replies', 'Admin\AdminReplyController')->except('index', 'show');
        });
    });

    //course routes
    Route::resource('courses', 'CourseController');
    Route::get('courses_status', 'CourseController@index')->name('courses');

    //assignment routes
    Route::resource('assignments', 'AssignmentController');
    Route::resource('download', 'AssignmentDownloadController');
    Route::get('/download/download/{path}/', 'AssignmentDownloadController@downloadClientFile')->name('download-assignment-file');

    //reviewed assignments
    Route::resource('reviewed_assignments', 'ReviewedAssignmentController');

    //profile page for user
    Route::resource('profile', 'ProfileController');

    //forum routes
    Route::prefix('forum')->group(function () {
        Route::get('/', 'TopicController@index')->name('forum');
        Route::get('/my-posts', 'ForumPostController@index')->name('my-posts');
        Route::resource('topics', 'TopicController');
        Route::resource('topics.posts', 'ForumPostController')->except('index');
        Route::resource('topics.posts.replies', 'ReplyController')->except('index', 'show');
    });
});

resources/views/layouts/partials/nav.blade.php
<!-- Sidebar -->
<div class="border-right" id="sidebar-wrapper">
    <div class="sidebar-heading">
        <a href="{{route('home')}}">
            <img src="{{ asset('images/sidenav-logo.png') }}">
        </a>
    </div>
    <div class="list-group list-group-flush">
        <a href="{{route('courses.index')}}"

           class="{{ Route::currentRouteNamed('courses.index') ? 'active' : '' }} nav-item nav-link">Cursussen</a>
        <a href="{{route('reviewed_assignments.index')}}" class="{{ Route::currentRouteNamed('reviewed_assignments.index') ? 'active' : '' }} nav-item nav-link">Beoordelingen</a>
        <a href="{{route('forum')}}" class="{{ Route::currentRouteNamed('forum') ? 'active' : '' }} nav-item nav-link">Forums</a>
        <a href="{{route('my-posts')}}" class="{{ Route::currentRouteNamed('my-posts') ? 'active' : '' }} nav-item nav-link">Mijn posts</a>
        <a href="{{route('profile.index') }}" class="{{ Route::currentRouteNamed('profile.index') ? 'active' : '' }} nav-item nav-link"> {{ Auth::user()->name }}</a>


        <!-- If user is teacher or admin -->
    @if(Auth::user()->roles_id == 3 || Auth::user()->roles_id == 2)
            <p class="text-muted border-bottom ml-1">Docent</p>
            <!--  admin or teacher user navlinks -->
            <a href="{{route('admin.courses.create')}}"
               class="{{ Route::currentRouteNamed('admin.courses.create') ? 'active' : '' }} nav-item nav-link">
                Nieuwe cursus aanmaken</a>
            <a href="{{route('admin.made_assignments.index')}}"
               class="{{ Route::currentRouteNamed('admin.made_assignments.index') ? 'active' : '' }} nav-item nav-link">
                Gemaakte opdrachten</a>
            <a href="{{route('admin.courses.index')}}"
               class="{{ Route::currentRouteNamed('admin.courses.index') ? 'active' : '' }} nav-item nav-link">
                Beheer Cursussen</a>
            <a href="{{route('admin.topics.index')}}"
               class="{{ Route::currentRouteNamed('admin.topics.index') ? 'active' : '' }} nav-item nav-link">
                Beheer Forums</a>
            <a href="{{route('admin.notifications.index')}}"
               class="{{ Route::currentRouteNamed('admin.notifications.index') ? 'active' : '' }} nav-item nav-link">
                Beheer Homepage Meldingen</a>

            <!--  admin or teacher user navlinks -->
    @endif

    <!-- if user is admin -->
    @if(Auth::user()->roles_id == 3)
            <p class="text-muted border-bottom ml-1">Admin</p>
            <!--  admin user navlinks -->
            <a href="{{route('admin.roles_update.index')}}"
               class="{{ Route::currentRouteNamed('admin.roles_update.index') ? 'active' : '' }} nav-item nav-link">
                Verander Gebruikersrechten</a>
            <!-- admin user navlinks -->
        @endif


        <a class="nav-item nav-link bottom-nav" href="{{ route('logout') }}"
           onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();">
            {{ __('Uitloggen') }}
        </a>

        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
        </form>
    </div>

</div>

<!-- /#sidebar-wrapper -->