routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});


Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

//check if the user is logged in
Route::group(['middleware' => ['auth']], function () {

    //put admin. in front of every admin route
    Route::prefix('admin')->name('admin.')->group(function () {

        //admin-only routes
        Route::group(['middleware' => ['is_admin']], function () {
            Route::resource('roles_update', 'SuperAdmin\AdminRoleController');
        });

        //admin/teacher-only routes
        Route::group(['middleware' => ['is_teacher']], function () {
            //course management routes
            Route::resource('courses', 'Admin\AdminCourseController');

            //assignment management routes
            Route::resource('courses.assignments', 'Admin\AdminAssignmentController');
            Route::resource('made_assignments', 'Admin\AdminMadeAssignmentsController');
            Route::get('/made_assignments/download/{path}/', 'Admin\AdminMadeAssignmentsController@downloadClientFile')->name('download-file');

            //notification management routes
            Route::resource('notifications', 'Admin\AdminNotificationController')->except('show');

            //forum management routes
            Route::resource('topics', 'Admin\AdminTopicController');
            Route::resource('topics.posts', 'Admin\AdminForumPostController')->except('index');
            Route::resource('topics.posts.replies', 'Admin\AdminReplyController')->except('index', 'show');
        });
    });

    //course routes
    Route::resource('courses', 'CourseController');
    Route::get('courses_status', 'CourseController@index')->name('courses');

    //assignment routes
    Route::resource('assignments', 'AssignmentController');
    Route::resource('download', 'AssignmentDownloadController');
    Route::get('/download/download/{path}/', 'AssignmentDownloadController@downloadClientFile')->name('download-assignment-file');

    //reviewed assignments
    Route::resource('reviewed_assignments', 'ReviewedAssignmentController');

    //profile page for user
    Route::resource('profile', 'ProfileController');

    //forum routes
    Route::prefix('forum')->group(function () {
        Route::get('/', 'TopicController@index')->name('forum');
        Route::get('/my-posts', 'ForumPostController@index')->name('my-posts');
        Route::resource('topics', 'TopicController');
        Route::resource('topics.posts', 'ForumPostController')->except('index');
        Route::resource('topics.posts.replies', 'ReplyController')->except('index', 'show');
    });
});

resources/views/forum/forum_post_create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="mb-3">Bootcamp Forums</h1>

                <div class="card">
                    <div class="card-header h5">Nieuwe post plaatsen</div>

                    <div class="card-body">
                        <form action="{{ route('admin.topics.posts.store', $topic) }}" method="POST">
                            @csrf

                            <p>Je post wordt in deze topic geplaatst:<br>
                                {{ $topic->name }}
                            </p>

                            <label for="title">Naam van je post</label>
                            <input class="form-control" type="text" name="title" id="title"> <br>

                            <label for="message">Berichttekst</label>
                            <textarea class="form-control" type="text" name="message"
                                      id="message" rows="4"></textarea> <br>

                            <div class="mt-2">
                                <button type="submit" class="btn btn-primary">Opslaan</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/forum/forum_post_edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="mb-3">Bootcamp Forums</h1>

                <div class="card">
                    <div class="card-header h5">Post aanpassen</div>

                    <div class="card-body">
                        <form action="{{ route('topics.posts.update', [$topic, $forum_post])}}" method="POST">
                            @method('PATCH')
                            @csrf

                            <label for="title">Naam van je post</label>
                            <input class="form-control" type="text" name="title" id="title"
                                   value="{{ $forum_post->title}}"> <br>

                            <label for="message">Berichttekst</label>
                            <textarea class="form-control" type="text" name="message"
                                      id="message" rows="4">{{ $forum_post->message}}</textarea> <br>

                            <div class="mt-2">
                                <button type="submit" class="btn btn-primary">Opslaan</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/forum/forum_post_show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="h1 mb-3">Bootcamp Forums</div>

                <div class="h5 mt-2">
                    <a href="{{ route('topics.index') }}">Forums</a>
                    @foreach($path as $link)
                        > <a href="{{ route('topics.show', $link) }}">{{ $link->name }}</a>
                    @endforeach
                    > {{ $forum_post->title }}
                </div>

                <div class="card mb-3">
                    <div class="card-header border-bottom-0">
                        <div class="h4 mb-0">{{ $forum_post->title }}</div>
                    </div>

                    <div class="card-body border-top">
                        <div>{{ $forum_post->message }}</div> <br>

                        <div class="text-black-50">
                            Gepost door: {{ $forum_post->users->name }} <br>
                            Gepost op: {{ $forum_post->created_at }}

                            @if($forum_post->users_id == $user_id)
                                <div class="row mt-2">

                                    <a href="{{ route('topics.posts.edit', [$topic, $forum_post]) }}"
                                       class="btn btn-primary ml-3">Bewerk post</a>

                                    <form action="{{ route('topics.posts.destroy', [$topic, $forum_post])}}"
                                          method="POST">
                                        @method('delete')
                                        @csrf

                                        <button type="submit" class="btn btn-danger ml-2">
                                            Verwijder post
                                        </button>
                                    </form>
                                </div>
                            @endif
                        </div>
                    </div>

                    <div class="card-body border-top bg-light">
                        <a href="{{ route('topics.posts.replies.create', [$topic, $forum_post]) }}"
                           class="btn btn-primary mb-2">Reageer op dit bericht</a>

                        <div class="h5 mb-0">Reacties:</div>

                        <div class="mt-3">
                            <form action="{{route('topics.posts.show', [$topic, $forum_post])}}" method="get">
                                <select id="filter" name="sort" onchange="this.form.submit()">
                                    <option value="" disabled selected>Sorteer</option>
                                    <option value="message_asc">Bericht ↑</option>
                                    <option value="message_desc">Bericht ↓</option>
                                    <option value="name_asc">Naam ↑</option>
                                    <option value="name_desc">Naam ↓</option>
                                    <option value="created_at_asc">Datum ↑</option>
                                    <option value="created_at_desc">Datum ↓</option>
                                </select>
                            </form>
                        </div>
                    </div>

                    @foreach($replies as $reply)
                        <div class="card-body border-top">
                            <div>{{ $reply->message }}</div>
                            <br>
                            <div class="text-black-50 mb-1">
                                Gepost door: {{ $reply->users->name }} <br>
                                Gepost op: {{ $reply->created_at }}
                            </div>

                            @if($reply->users_id == $user_id)
                                <div class="row mt-2">
                                    <a href="{{ route('topics.posts.replies.edit', [$topic, $forum_post, $reply]) }}"
                                       class="btn btn-primary ml-3">Bewerk reactie</a>

                                    <form action="{{ route('topics.posts.replies.destroy', [$topic, $forum_post, $reply])}}"
                                        method="POST">
                                        @method('delete')
                                        @csrf

                                        <button type="submit" class="btn btn-danger ml-2">
                                            Verwijder reactie
                                        </button>
                                    </form>
                                </div>
                            @endif
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/forum/my_posts.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card mt-1">
                    @if($my_posts->isEmpty() == false)
                        <div class="card-header border-bottom-0">
                            <h4 class="mt-1">Mijn Posts</h4>
                        </div>

                        @foreach($my_posts as $post)
                            <a href="{{ route('topics.posts.show', [$post->topics_id, $post]) }}">
                                <div class="card-body border-top">
                                    {{ $post->title }}
                                </div>
                            </a>
                        @endforeach
                    @else
                        <div class="card-header border-bottom-0">
                            <h4 class="mt-1">Je hebt nog geen posts gemaakt</h4>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/forum/reply_create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="mb-3">Bootcamp Forums</h1>

                <div class="card">
                    <div class="card-header">
                        <h4 class="mt-1">Reageer op {{ $forum_post->title }}</h4>
                    </div>

                    <div class="card-body">
                        <form action="{{ route('topics.posts.replies.store', [$topic, $forum_post]) }}" method="POST">
                            @method('POST')
                            @csrf

                            <textarea class="form-control" type="text" name="message"
                                      id="message" required></textarea> <br>

                            <button type="submit" class="btn btn-primary">Plaats reactie</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/forum/reply_edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="mb-3">Bootcamp Forums</h1>

                <div class="card">
                    <div class="card-header">
                        <h4 class="mt-1">Bewerk je reactie op {{ $forum_post->title }}</h4>
                    </div>

                    <div class="card-body">
                        <form action="{{ route('topics.posts.replies.update', [$topic, $forum_post, $reply]) }}" method="POST">
                            @method('PATCH')
                            @csrf

                            <textarea class="form-control" type="text" name="message"
                                      id="message" required>{{ $reply->message }}</textarea> <br>

                            <button type="submit" class="btn btn-primary">Bewerk reactie</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/forum/topic_show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="h1 mb-3">Bootcamp Forums</div>

                <div class="h5 mt-2">
                    <a href="{{ route('topics.index') }}">Forums</a>
                    @foreach($path as $link)
                        > <a href="{{ route('topics.show', $link) }}">{{ $link->name }}</a>
                    @endforeach
                    > {{ $show_topic->name }}
                </div>

                @if($topics->isEmpty() == false)
                    <div class="card mb-3">
                        <div class="card-header border-bottom-0">
                            <div class="h4 mb-0">Onderwerpen</div>

                            <div class="mt-3">
                                <form action="{{route('topics.show', $show_topic)}}" method="get">
                                    <select id="filter" name="sort_topics" onchange="this.form.submit()">
                                        <option value="" disabled selected>Sorteer</option>
                                        <option value="name_asc">Naam ↑</option>
                                        <option value="name_desc">Naam ↓</option>
                                        <option value="created_at_asc">Datum ↑</option>
                                        <option value="created_at_desc">Datum ↓</option>
                                    </select>
                                </form>
                            </div>
                        </div>

                        @foreach($topics as $topic)
                            <a class="h6 mb-0" href="{{ route('topics.show', $topic) }}">
                                <div class="card-body border-top">
                                    {{ $topic->name }}
                                </div>
                            </a>
                        @endforeach
                    </div>
                @endif

                @if($forum_posts->isEmpty() == false)
                    <div class="card mb-3">
                        <div class="card-header border-bottom-0">
                            <div class="h4 mb-0">Posts</div>

                            <a href="{{ route('topics.posts.create', $show_topic) }}"
                               class="btn btn-primary mt-2">Maak een nieuwe post</a>

                            <div class="mt-3">
                                <form action="{{route('topics.show', $show_topic)}}" method="get">
                                    <select id="filter" name="sort_posts" onchange="this.form.submit()">
                                        <option value="" disabled selected>Sorteer</option>
                                        <option value="title_asc">Titel ↑</option>
                                        <option value="title_desc">Titel ↓</option>
                                        <option value="created_at_asc">Datum ↑</option>
                                        <option value="created_at_desc">Datum ↓</option>
                                    </select>
                                </form>
                            </div>
                        </div>

                        @foreach($forum_posts as $forum_post)
                            <a class="h6 mb-0" href="{{ route('topics.posts.show', [$show_topic, $forum_post]) }}">
                                <div class="card-body border-top">
                                    {{ $forum_post->title }}
                                </div>
                            </a>
                        @endforeach
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/forum/topics.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="h1 mb-3">Bootcamp Forums</div>

                <div class="h5 mt-2">
                    Forums
                </div>

                <div class="card mb-3">
                    <div class="card-header border-bottom-0">
                        <div class="h4 mb-0">Onderwerpen</div>

                        <div class="mt-3">
                            <form action="{{route('topics.index')}}" method="get">
                                <select id="filter" name="sort_topics" onchange="this.form.submit()">
                                    <option value="" disabled selected>Sorteer</option>
                                    <option value="name_asc">Naam ↑</option>
                                    <option value="name_desc">Naam ↓</option>
                                    <option value="created_at_asc">Datum ↑</option>
                                    <option value="created_at_desc">Datum ↓</option>
                                </select>
                            </form>
                        </div>
                    </div>

                    @foreach($topics as $topic)
                        <a class="h6 mb-0" href="{{ route('topics.show', $topic) }}">
                            <div class="card-body border-top">
                                {{ $topic->name }}
                            </div>
                        </a>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endsection